server:
  port: 19176
spring:
  # rest编码
  http.encoding:
    charset: UTF-8
    force: true
    # 文件上传本地配置
  servlet.multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 50MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true