server:
  port: 19176
spring:
  # rest编码
  http.encoding:
    charset: UTF-8
    force: true
    # 文件上传本地配置
  servlet.multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 50MB
    # 调用链追踪采集比例，上报地址在配置中心
  sleuth.sampler.probability: 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true